---
- name: Configure daemon.json
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0600"
    owner: root
    group: root
  notify: Restart Docker Service
