---
- name: Install required PIP packages
  pip:
    name: "{{ required_pip_packages }}"
    state: present

- include_tasks: install-Debian.yml
  when: ansible_os_family | lower in apt_distros
  tags: ['install-icinga2-stack', 'install-icinga2']
