---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  tags:
    - always
    - install
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: install.yml

- include_tasks: configure.yml

- name: Ensure that Docker Daemon is started and enabled on boot
  service:
    name: docker.service
    state: started
    enabled: "{{ docker_enable_on_boot }}"
